########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
########################### SECRETS
secrets:
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
  influx_password:
    file: $DOCKERDIR/secrets/influx_password
  influx_admin_token:
    file: $DOCKERDIR/secrets/influx_admin_token

include:
  ########################### SERVICES
  # PREFIX udms = Ultimate Docker Media Server
  # HOSTNAME=udms - defined in .env


  # CORE
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/portainer.yml
  - compose/$HOSTNAME/dozzle.yml
  - compose/$HOSTNAME/homepage.yml
  - compose/$HOSTNAME/homarr.yml


  #Media
  - compose/$HOSTNAME/plex.yml

  #PVRs
  - compose/$HOSTNAME/radarr.yml
  - compose/$HOSTNAME/sonarr.yml
  - compose/$HOSTNAME/bazarr.yml
  - compose/$HOSTNAME/prowlarr.yml
  - compose/$HOSTNAME/unpackerr.yml

  #Network Services
  - compose/$HOSTNAME/pihole.yml

  # Brewing House
  - compose/$HOSTNAME/brewhouse-monitoring/influxdb.yml
  - compose/$HOSTNAME/brewhouse-monitoring/grafana.yml

  #Home Automation
  - compose/$HOSTNAME/homeassistant.yml
